# Generated by Django 2.0.5 on 2018-08-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='font_size',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
