# Generated by Django 2.0.5 on 2018-08-10 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_snippet_font_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
